import { defineContentConfig, defineCollection, z } from '@nuxt/content'

export default defineContentConfig({
  collections: {
    authors: defineCollection({
      type: 'page',
      source: 'authors/*.md',
      schema: z.object({
        name: z.string(),
        createdAt: z.string(),
      }),
    }),
    projects: defineCollection({
      type: 'page',
      source: 'projects/*/index.md',
      schema: z.object({
        title: z.string(),
        status: z.enum(['active', 'on-hold']).default('active'),
        icon: z.string().optional(),
        tags: z.array(z.string()).default([]),
        description: z.string().optional(),
        githubRepo: z.string().optional(),
        createdAt: z.string(),
        updatedAt: z.string().optional(),
        availableStatuses: z.array(z.string()).optional(),
        defaultStatus: z.string().optional(),
        defaultPriority: z.string().optional(),
        defaultAssignee: z.string().optional(),
        pinned: z.boolean().optional(),
        pinnedOrder: z.number().optional(),
        archivedAt: z.string().optional(),
      }),
    }),
    docs: defineCollection({
      type: 'page',
      source: 'projects/*/docs/*.md',
      schema: z.object({
        title: z.string(),
        tags: z.array(z.string()).default([]),
        parent: z.string().optional(),
        isFolder: z.boolean().optional(),
        order: z.number().default(0),
        createdAt: z.string(),
        updatedAt: z.string().optional(),
        archivedAt: z.string().optional(),
      }),
    }),
    standalone_docs: defineCollection({
      type: 'page',
      source: 'docs/*.md',
      schema: z.object({
        title: z.string(),
        tags: z.array(z.string()).default([]),
        parent: z.string().optional(),
        isFolder: z.boolean().optional(),
        order: z.number().default(0),
        createdAt: z.string(),
        updatedAt: z.string().optional(),
        archivedAt: z.string().optional(),
      }),
    }),
    tasks: defineCollection({
      type: 'page',
      source: 'projects/*/tasks/*.md',
      schema: z.object({
        title: z.string(),
        status: z.enum(['todo', 'in-progress', 'in-review', 'done', 'blocked', 'on-hold']).default('todo'),
        priority: z.enum(['low', 'medium', 'high', 'urgent']).default('medium'),
        tags: z.array(z.string()).default([]),
        assignees: z.array(z.string()).default([]),
        due: z.string().optional(),
        dependencies: z.array(z.string()).default([]),
        githubIssues: z.array(z.number()).default([]),
        githubPRs: z.array(z.number()).default([]),
        createdAt: z.string(),
        updatedAt: z.string().optional(),
        archivedAt: z.string().optional(),
        order: z.number().default(0),
      }),
    }),
  },
})
